### ISSUE TITLE
confusing duplicate bin and config directories

### ISSUE THREAD

**Issue by petere** [MathYourLife/kafka_broker#20]
A default installation (checked via the provided Test Kitchen suites) creates both

```
/usr/local/kafka/config/
/usr/local/kafka/bin/
```

as well as

```
/usr/local/kafka/kafka_2.11-0.8.2.1/config/
/usr/local/kafka/kafka_2.11-0.8.2.1/bin/
```

which contain partially overlapping but slightly different content.  And it takes quite some detective work by the casual admin to determine and verify which of these are actually used.

The former are of course created by this cookbook.  If the cookbook thinks those are valuable, it should probably delete the duplicates under `/usr/local/kafka/kafka_2.11-0.8.2.1/`.

**Comment by mathyourlife** [comment]
Thanks for the feedback @petere. The files in 

```
/usr/local/kafka/kafka_2.11-0.8.2.1/config/
/usr/local/kafka/kafka_2.11-0.8.2.1/bin/
```

are from the tarball extract and while I've spent some time trying to use them directly, they unfortunately contain some hard coded config values that make it cumbersome to work with.  Yes, we could definitely delete those directories as part of the installation process, but since we don't yet have corresponding scripts for all `bin` executables in `/usr/local/kafka/bin/` They may be useful for some users to leave there.

**Comment by petere** [comment]
I'm OK with this explanation. I guess there is nothing to fix, but perhaps someone will find the explanation useful in the future.

**Comment by mathyourlife** [comment]
thanks @petere
