### ISSUE TITLE
Allow multiple brokers on the same host

### ISSUE THREAD

**Issue by mathyourlife** [MathYourLife/kafka_broker#7]
Modify the recipe to allow for multiple instances of the broker to operate on the same host by listening to different ports.

**Comment by mathyourlife** [comment]
Not sure if it is worth overcomplicating the cookbook to add this feature.  Is a benefit to this beyond for demo purposes of having multiple brokers?

**Comment by justizin** [comment]
Maybe run the recipe in three containers?

**Comment by mathyourlife** [comment]
yeah, three containers/hosts/whatevers seems preferable to adding this

**Comment by justizin** [comment]
If you want to check out my wrapper cookbook, it has a Vagrantfile which does this:

  https://github.com/bitmonk/bitmonk_kafka

It still has issues, this is basically where my PRs are coming from.  Probably could be more lightweight with docker instead of virtualenv backend.

**Comment by vkhatri** [comment]
@MathYourLife +1, adding capability of provisioning more than one broker on a chef node is indeed going to over complicate the cookbook functionality.

i like the cookbook better with a single broker setup per chef node and docker seems like a good candidate to achieve otherwise. 

could you please update this issue on which direction we are going?

**Comment by mathyourlife** [comment]
Closing. Won't fix.
